@Identity_HostAddress = https://localhost:7023

GET {{Identity_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Identity_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterDto
}

###


POST {{Identity_HostAddress}}/api/roles/createrole
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MTQwNSwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.sNshEq3jChY-dk2boLjHFSTeHLo3s4I2Brl1jmgcA0M
Content-Type: application/json
{
  "name": "Manager",
  "description": "Manager should manage the team."
}
###

GET {{Identity_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U

###

POST {{Identity_HostAddress}}/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U
Content-Type: application/json

{
  "email": "naina@gmail.com",
  "password": "sneha@12345",
  "name": "Naina",
  "phone": "7865438709"
}

###

@id=4
GET {{Identity_HostAddress}}/api/users/{{id}}

###

PUT {{Identity_HostAddress}}/api/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MTQwNSwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.sNshEq3jChY-dk2boLjHFSTeHLo3s4I2Brl1jmgcA0M
Content-Type: application/json
{
  "name": "Shamiksha",
  "phone": "7865439876",
  "isActive": true
}

###

DELETE {{Identity_HostAddress}}/api/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MTQwNSwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.sNshEq3jChY-dk2boLjHFSTeHLo3s4I2Brl1jmgcA0M

###

GET {{Identity_HostAddress}}/api/users/3/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MTQwNSwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.sNshEq3jChY-dk2boLjHFSTeHLo3s4I2Brl1jmgcA0M

###

GET {{Identity_HostAddress}}/api/users/3/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MTQwNSwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.sNshEq3jChY-dk2boLjHFSTeHLo3s4I2Brl1jmgcA0M

###

GET {{Identity_HostAddress}}/api/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MjYzMywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.LR1Z23Vf8Ap49SZ1CPplALQRNx84MyDCDP6TycYrXm8

###

GET {{Identity_HostAddress}}/api/roles/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MjYzMywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.LR1Z23Vf8Ap49SZ1CPplALQRNx84MyDCDP6TycYrXm8

###

DELETE {{Identity_HostAddress}}/api/roles/4/deleterole
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MjYzMywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.LR1Z23Vf8Ap49SZ1CPplALQRNx84MyDCDP6TycYrXm8

###

POST {{Identity_HostAddress}}/api/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U
Content-Type: application/json

 { "name": "AssignPermission", "description": "Assign permissions to roles" }

 ###

POST {{Identity_HostAddress}}/api/roles/3/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U
Content-Type: application/json

{
  "roleId": 3,
  "permissionId": [
    1,2,3,4,5
  ]
}

###

GET {{Identity_HostAddress}}/api/roles/3/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U

###

GET {{Identity_HostAddress}}/api/roles/3/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U

###

PUT {{Identity_HostAddress}}/api/roles/3/updaterole
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc3Nzc0MzQ4MCwiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.oRvpMScJgAbe_12g0DbYh2tzPox2XSCjWLugX62CO3U
Content-Type: application/json
{
  "name": "Admin",
  "description": "Super admin have all access"
}

###

GET {{Identity_HostAddress}}/api/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsiQ3JlYXRlVXNlciIsIlVwZGF0ZVVzZXIiLCJEZWxldGVVc2VyIiwiVmlld1VzZXIiLCJDcmVhdGVSb2xlIl0sImV4cCI6MTc3Nzc0NTk5MywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.cEni_fHdP6pUtM720WdPhWK1OmvcEeWesauGfW45B4g
###

GET {{Identity_HostAddress}}/api/permissions/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsiQ3JlYXRlVXNlciIsIlVwZGF0ZVVzZXIiLCJEZWxldGVVc2VyIiwiVmlld1VzZXIiLCJDcmVhdGVSb2xlIl0sImV4cCI6MTc3Nzc0NTk5MywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.cEni_fHdP6pUtM720WdPhWK1OmvcEeWesauGfW45B4g

###

@permissionId=0
GET {{Identity_HostAddress}}/api/permissions/{id}/roles?permissionId={{permissionId}}

###

GET {{Identity_HostAddress}}/api/permissions/2/roles?permissionId={{permissionId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsiQ3JlYXRlVXNlciIsIlVwZGF0ZVVzZXIiLCJEZWxldGVVc2VyIiwiVmlld1VzZXIiLCJDcmVhdGVSb2xlIl0sImV4cCI6MTc3Nzc0NTk5MywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.cEni_fHdP6pUtM720WdPhWK1OmvcEeWesauGfW45B4g

###

GET {{Identity_HostAddress}}/api/permissions/{id}/roles?permissionId={{permissionId}}

###

GET {{Identity_HostAddress}}/api/permissions/{id}/roles?permissionId={{permissionId}}

###

GET {{Identity_HostAddress}}/api/permissions/2/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsiQ3JlYXRlVXNlciIsIlVwZGF0ZVVzZXIiLCJEZWxldGVVc2VyIiwiVmlld1VzZXIiLCJDcmVhdGVSb2xlIl0sImV4cCI6MTc3Nzc0NTk5MywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.cEni_fHdP6pUtM720WdPhWK1OmvcEeWesauGfW45B4g

###

GET {{Identity_HostAddress}}/api/permissions/2/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJtZWhha0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIlBlcm1pc3Npb24iOlsiQ3JlYXRlVXNlciIsIlVwZGF0ZVVzZXIiLCJEZWxldGVVc2VyIiwiVmlld1VzZXIiLCJDcmVhdGVSb2xlIl0sImV4cCI6MTc3Nzc0NTk5MywiaXNzIjoiSWRlbnRpdHlTeXN0ZW0iLCJhdWQiOiJTdXJ2ZXlVc2VycyJ9.cEni_fHdP6pUtM720WdPhWK1OmvcEeWesauGfW45B4g

###
