@Identity_HostAddress = https://localhost:7023

GET {{Identity_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Identity_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterDto
}

###
